### ISSUE TITLE
All lunr-languages included in build, even when just using 'en'

### ISSUE THREAD

**Issue by macandcheese** [humanseelabs/gatsby-plugin-lunr#17]
The enhanceLunr function in `common.js` seems to include all the lunr-language packages in the built site, even if 'en' is the only language used in the `gatsby-config`:

```
 {
      resolve: 'gatsby-plugin-lunr',
      options: {
        languages: [{
          name: 'en',
          filterNodes: (node) => ((node.frontmatter) && (node.frontmatter.status && node.frontmatter.status === 'published'))
        }],
        fields: [
        ...
}
```

Still builds with the lunr-language files:

![Bitmap](https://user-images.githubusercontent.com/4733155/55362857-238d5700-5490-11e9-9354-904e64a60b5f.png)

Temporarily, I've moved the plugin to `/plugins` folder and commented out the function in order to build the site without lunr-languages, but I'm curious if there's a change I can make to my syntax to achieve this.

**Comment by bradleyayers** [comment]
This happens due to the way webpack does static analyses on dynamic `require()` calls, and in particular its understanding of the pattern `require('foo' + bar)`. In this case it will include everything starting with `foo`, since it has no way of knowing possible values of `bar`.

So the code:

```
require(`lunr-languages/lunr.${name}`)(lunr)
```

causes webpack to include `lunr-languages/lunr.*`.

**Comment by macandcheese** [comment]
Thank you for putting this fix in place so quickly!
